stages:
  - build
  - deploy

web:build:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main

pages:
  stage: deploy
  image: alpine:latest
  script:
    - rm -r public
    - cp dist/index.html dist/404.html
    - mv ./dist ./public
  artifacts:
    paths:
      - public
  only:
    - main
