stages:
  - build
  - pages

build:
  image: node:16
  state: build
  script:
    - npm ci
    - npm build
  artifacts:
    paths:
      - dist
  only:
    - main

pages:
  image: alpine:latest
  stage: deploy
  script:
    - echo "Deploying"...
    - mv dist public
  artifacts:
    paths:
      - public
  tags:
    - Pages
  only:
    - main

